### ISSUE TITLE
Encoding a piece of data succeeds, decoding throws invalid parameter

### ISSUE THREAD

**Issue by minkjaco** [jkent/python-bchlib#10]
When I successfully encode some data, 0-padded to ensure it is format-able as a bytearray, then attempt to decode it, the decode function throws an invalid parameter error. 

Although, I haven't been able to decipher what specifically causes the error, I think it has something to do with the choice of input length and not necessarily forcing it to a power of 2. Here I choose the input length to be the smallest possible, k = n - m*t.

Could the decode function be restricted to a power of 2 length input, and if this is the case, why does the encode function accept input that is not a power of 2?

Here is a (somewhat) minimal example:

```
import bchlib
from bitstring import BitArray
from numpy.random import uniform
//correct 60 errors
bch = bchlib.BCH(8219, 60)
# create random data at smallest allowable length by bch params
data = [0 if uniform() > .5 else 1 for x in range(0, bch.n - bch.m*bch.t)]
bi = BitArray(data)
# 0 pad to full byte
if len(bi) % 8 != 0:
    bi.prepend('0b', + '0' * (8 - (len(bi) % 8)))
by = bytearray(bi)

# encode
parity = bch.encode(by)

# decode throw ValueError: invalid parameters
bch.decode(by, parity)
```

Thanks!

**Comment by jkent** [comment]
Hi minkjaco,

I played around with your example; I don't know why encode is works and decode fails in this case.  I haven't used the BCH code outside of correcting NAND blocks.  The BCH code is the same code provided with the Linux Kernel.  Sorry I don't have an answer for you.  If you can get the same results using the C code, Ivan Djelic might be able to assist you.

**Comment by minkjaco** [comment]
Thanks! Is there an email I can reach him at?

**Comment by jkent** [comment]
Yep.  Ivan Djelic <ivan.djelic@parrot.com>

**Comment by minkjaco** [comment]
Thanks, I'll go ahead and close this.

**Comment by dj-on-github** [comment]
The bch.c code still has this behavior. bch_encode It is limiting the the number of message bits rounded down to the next byte boundary instead of rounded up and zero padded with bits. So for example with BCH(255,131,18) you can only use a 128 bit message, when BCH supports a 131 bit message. This seems like a bug to me. It's on lines 1060-1062 in bch.c

	/* sanity check: make sure data length can be handled */
	if (8*len > (bch->n-bch->ecc_bits))
		return -EINVAL;

Here : https://github.com/jkent/python-bchlib/blob/master/src/bch.c

**Comment by Michael-Esser777** [comment]
I know this is old but any chance you know how to fix this? I'm having the same issue and i'm pretty sure that is the problem.

> The bch.c code still has this behavior. bch_encode It is limiting the the number of message bits rounded down to the next byte boundary instead of rounded up and zero padded with bits. So for example with BCH(255,131,18) you can only use a 128 bit message, when BCH supports a 131 bit message. This seems like a bug to me. It's on lines 1060-1062 in bch.c
> 
> ```
> /* sanity check: make sure data length can be handled */
> if (8*len > (bch->n-bch->ecc_bits))
> 	return -EINVAL;
> ```
> 
> Here : https://github.com/jkent/python-bchlib/blob/master/src/bch.c

**Comment by jkent** [comment]
Hi @Michael-Esser777 

I've tried to fix this in the past, but I had to revert the change as it broke the tests in some edge cases, such as errors in the first byte of the message.

**Comment by Michael-Esser777** [comment]
Ok thank you for your response. I found a work around by just shortening the message by a bit which will work for my application.
