### ISSUE TITLE
Compilation broken under Visual Studio (2015)

### ISSUE THREAD

**Issue by jeffreycordero** [jkent/python-bchlib#11]
As shown, I am unable to install due to compilation errors. In case this makes any sense to you?

![image](https://user-images.githubusercontent.com/22757515/49532190-8fb0d300-f881-11e8-8621-417629d9911f.png)

**Comment by jkent** [comment]
I don't have time right now to work on this, but compiling with visual studio is currently broken.  I'll leave this issue open and come back to this sometime in the future.

**Comment by tongshiwen** [comment]
I also encountered this problem, how can I solve it?

**Comment by jkent** [comment]
I'm feeling ambitious today.. I'll look into this

**Comment by tongshiwen** [comment]
Thanks, I look forward to @jkent,

**Comment by jkent** [comment]
Fixed in commit 42e8d9f!
