### ISSUE TITLE
 error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

### ISSUE THREAD

**Issue by Maulshree27** [jkent/python-bchlib#12]
While trying to pip install bchlib, it is giving the above error. Please let me know how to proceed further

**Comment by jkent** [comment]
Hi @Maulshree27, I just added Windows support today.  You should be able to install with pip now after installing [Visual Studio 2015 Community Edition](https://go.microsoft.com/fwlink/?LinkId=532606&clcid=0x409).
