### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by tongshiwen** [jkent/python-bchlib#13]
Hello @jkent，I use python35 for decoding under Windows10, there is a bug running here" bitflips = bch.decode_inplace(data, ecc)",  the bug is "Segmentation fault", hou can I solve it?

**Comment by jkent** [comment]
Sorry about that, I introduced a bug.  I deleted that release and uploaded 0.10.  Please try now.

**Comment by tongshiwen** [comment]
Thank you!@jkent
