### ISSUE TITLE
Loop over polynomial combinations

### ISSUE THREAD

**Issue by cpbridges** [jkent/python-bchlib#16]
I'm working with some existing code that takes 512 bits and generates a 20 bit BCH syndrome. It looks like the polynomial is either a 1 long value or 4 x 10 bit values.

Is there any try/catch method to loop over polynomials like this:
```
for poly in range(1,1000):
    try:
        bch = bchlib.BCH(poly, 20)
        print('found')
    except:
        # Do nothing
```
This unfortunately crashes. Is there any alt way? Thanks!

**Comment by jkent** [comment]
Sorry for getting back so late.  I probably should put a check for this in there, but a rule of thumb is that the polynomial must start and end with a 1 bit.  This means the polynomial must be an odd number.  If you change to ```range(1, 1000, 2)``` it won't segfault.  Hope that helps!
