### ISSUE TITLE
Getting Runtime error on entering large values for t

### ISSUE THREAD

**Issue by ShubhamShekhar123** [jkent/python-bchlib#17]
If we are providing large values for t say,

bch = bchlib.BCH(2341,1018), we are getting following Runtime error: 

RuntimeError: unable to inititalize BCH, bad parameters?
2019-12-04 11:39:52,788 ERROR RuntimeError	polynomial:2341	degree of polynomial:11	error bits t:1018
Traceback (most recent call last):
  File "<stdin>", line 25, in <module>

**Comment by jkent** [comment]
You're probably hitting this constraint in bch.c:

	if ((t < 1) || (m*t >= ((1 << m)-1)))
		/* invalid t value */
		goto fail;

You're requesting a correction bit strength (t) that is too high for the polynomial selected.  This is not a bug.

**Comment by ShubhamShekhar123** [comment]
Thanks for the reply. Yes, it was not a bug. I went through the code and found that you have actually added a constraint for value of t.
