### ISSUE TITLE
bchlib doesn't export any methods in Python3

### ISSUE THREAD

**Issue by Luluno01** [jkent/python-bchlib#2]
Hi, I was trying to build and test this module by running `python3 setup.py build` and `python3 encode-example.py`, but it ended up the following error message:

```
Traceback (most recent call last):
  File "encode-example.py", line 22, in <module>
    ecc = bchlib.bch(ECC_POLY, ECC_BITS)
AttributeError: module 'bchlib' has no attribute 'bch'
```

I checked out this module in Python3 interactive shell and found no method was exported by `bchlib`. Lately I found  `static PyMethodDef module_methods[]` in file bchlib.c contains no methods. I don't know  if this is the reason why `bchlib` doesn't export any methods in Python3.

Much appreciated. : )

**Comment by jkent** [comment]
Looks like its experienced some bitrot, I'll look into fixing it later today (GMT-6)

**Comment by Luluno01** [comment]
Thank you for your reply. I am looking forward to the next version. Great thanks!

**Comment by jkent** [comment]
Hmm, I looked it over again this afternoon, and it seems to be working fine under python3.5.
I did the following:
```
python3 setup.py build
ln -s build/lib.linux-x86_64-3.5/bchlib.cpython-35m-x86_64-linux-gnu.so bchlib.so
python3 encode-example.py
```

Python 2 seems to be broken though.

**Comment by Luluno01** [comment]
Aha, I'm using Python3.7, which is the latest alpha version of Python3. Maybe I should downgrade my Python3 XD. Thank you very much! I will this try again with Python 3.5.
