### ISSUE TITLE
RuntimeError: unable to inititalize bch, invalid parameters?

### ISSUE THREAD

**Issue by dimitrisdermanis** [jkent/python-bchlib#33]
I 've user bchlib before but when trying to use it now (fresh install / other system) I keep getting this error when running:
```python
>> bch = bchlib.BCH(8219, 16)
>> RuntimeError: unable to inititalize bch, invalid parameters?
```
The numbers dont really matter. I know that I use the lib correctly because I 've used it and the code is the same.

**Comment by jkent** [comment]
Usage has changed with a major version bump.  Use older version or see help() documentation in the Python REPL or unit tests for details.

This would be the new way:

    bch = bchlib.BCH(16, prim_poly=8219)

**Comment by dimitrisdermanis** [comment]
Thank you, it works. I see other changes as well. I guess I have to review my old code.
My issue is resolved.
