### ISSUE TITLE
Consecutive bch.decode calls lead to wrong output

### ISSUE THREAD

**Issue by Lukas113** [jkent/python-bchlib#35]
Using bchlib=1.0.0 & python=3.12, I've found that consecutive calls of `bch.decode` of the same `bch` instance results most likely in wrong outputs. Steps to reproduce:

Consecutive `bch.decode` calls:
```python
>>> from bchlib import BCH
>>> from bitstring import Bits
>>> bch = BCH(t=16, prim_poly=8219)
>>> data = Bits(b"First").tobitarray()
>>> ecc = bch.encode(data)
>>> data2 = Bits(b"Second").tobitarray()
>>> ecc2 = bch.encode(data2)
>>> print(f"n-errors data: {bch.decode(data, ecc)}")
n-errors data: 0
>>> print(f"n-errors data2: {bch.decode(data2, ecc2)}")
n-errors data2: -1
```
I also added `bch.correct` in between the decoding steps in case some cleanup would be done there. However, the result is the same.

Same as above, but without the first `bch.decode` call:
```python
>>> from bchlib import BCH
>>> from bitstring import Bits
>>> bch = BCH(t=16, prim_poly=8219)
>>> data = Bits(b"First").tobitarray()
>>> ecc = bch.encode(data)
>>> data2 = Bits(b"Second").tobitarray()
>>> ecc2 = bch.encode(data2)
>>> # print(f"n-errors data: {bch.decode(data, ecc)}")
>>> print(f"n-errors data2: {bch.decode(data2, ecc2)}")
n-errors data2: 0
```
Testing this using bchlib=0.14.0 worked fine as expected.

**Comment by jkent** [comment]
Hi Lukas113,

bchlib works with octets, not raw bits.  This issue may be because you are using 'bitstring.Bits' instead of a `bytes` or `bytearray` object, and the C wrapper may need more error checking on the data type.  To be honest, I've never used a Bits object.  I'll check this out.

**Comment by jkent** [comment]
OK, reproduced this with 'bytes' so there must be some state being kept between consecutive calls.

**Comment by jkent** [comment]
I understand why it's not working now.  Before decoding, the encode function required you to set your message length: `bch.data_len = 0`.  The first invocation, it was 0, and bch.data_len got set to len(data) on the first run.  Amusingly, "First" and "Secon" would have worked as expected.  It was the length that threw things off.

Since this is a very bad API decision, I've removed data_len.
