### ISSUE TITLE
any pre-compiled packages for 2.x.x?

### ISSUE THREAD

**Issue by narugo1992** [jkent/python-bchlib#38]
the newest bchlib cannot be installed on many systems, even on win11, it requires vs2022+'s cl to compile.

if pre-compiled version can be provided on pypi like before it would be much better.

**Comment by narugo1992** [comment]
i think this is because the github workflow has changed

some facts:
1. v1.0.0 version has full pre-compiled wheels
2. since v2, no pre-compiled wheels, only .tar.gz source code

i just compared the github workflow between these versions, no significant differences.

even in your newest deploy job: https://github.com/jkent/python-bchlib/actions/runs/10260838260

all the pre-compiled packages are made properly and uploaded to `artifacts`.

but in newest github workflow, the artifacts built in different os are uploaded to different artifact storage.

![image](https://github.com/user-attachments/assets/cb76ecfb-bd1e-437b-8478-7d95b35e53f2)

and your `upload_pypi` workflow only download the `artifacts` storage and upload it to pypi.

https://github.com/jkent/python-bchlib/blob/main/.github/workflows/github-deploy.yml#L60

thats why in newest versions, pre-compiled wheels are missing.

**Comment by jkent** [comment]
Sorry about that!  They're on PyPI now.
