### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Vyshak-S** [jkent/python-bchlib#4]
I am getting an installation error and not sure why. I have searched high and low but not able to fix this. Please help.

![image](https://user-images.githubusercontent.com/35913844/35498136-165cd8a0-04f3-11e8-99a2-3cf956000123.png)

**Comment by jkent** [comment]
I'm not supporting compilation with visual studio, sorry.  I'll leave this issue up for anyone brave enough to tackle it.

**Comment by jkent** [comment]
Closing this, it was for python 2.7 which WAS broken

**Comment by jkent** [comment]
I just wanted to let you know that Windows and Visual Studio 2015 is now supported.
