### ISSUE TITLE
Error when creating BCH(n=127, k=99)

### ISSUE THREAD

**Issue by mojganaz** [jkent/python-bchlib#8]
I want to create a code with n=127 and k=99. For this I run the following
bch = bchlib.BCH(128,4)
and then I get segmentation fault!
Am I missing something?

**Comment by jkent** [comment]
BCH takes two arguments, a polynomial, from which the galois field is determined automatically (5 to 15), and a correction strength in number of bits (t).  There is no n and k in my library.  Please refer to the README.md which has a complete usage example of the library.

**Comment by jkent** [comment]
To be fair it should not fault, but your usage was completely incorrect.

**Comment by mojganaz** [comment]
Sure, but I am a newbie and I am not sure how to compute the polynomial that generates such code. Could you please elaborate on this?

**Comment by jkent** [comment]
Best to use one of the "standard" polynomials if you do not understand them, can be found here:  https://github.com/jkent/python-bchlib/blob/master/bchlib/bch.c#L1308-L1312. they are m=5 thru m=15

I don't fully understand BCH myself, which is why I used Ivan's code from the Linux kernel.  This code was intended to make correcting NAND flash dumps easy, but has general purpose use as well.

**Comment by ovgeorge** [comment]
The link is dead and converting binary to int (binary representation produced by matlab's bchgenpoly(15,7) 
is not working and giving "RuntimeError: unable to inititalize BCH, bad parameters?" 


> Best to use one of the "standard" polynomials if you do not understand them, can be found here: https://github.com/jkent/python-bchlib/blob/master/bchlib/bch.c#L1308-L1312. they are m=5 thru m=15
> 
> I don't fully understand BCH myself, which is why I used Ivan's code from the Linux kernel. This code was intended to make correcting NAND flash dumps easy, but has general purpose use as well.

**Comment by ovgeorge** [comment]
Ok, it seems minimal value of m = 5 and for BCH(15,7) I need m = 4 
Bad luck, I guess.
