### ISSUE TITLE
Bad Parameters errors with valid polynomials?

### ISSUE THREAD

**Issue by dj-on-github** [jkent/python-bchlib#9]
https://link.springer.com/content/pdf/bbm%3A978-1-4899-2174-1%2F1.pdf list a large number of BCH parameters with their generator polynomials.

E.G. n=63, k=57, t=1, g=0x43 = 67 
>>> bch = bchlib.BCH(67,1)
>>> bch.m
6L

But when I use the values where t > 1, it fails.

E.G. n=63, k=51, t=2, g=0x1539 = 5433

>>> bch = bchlib.BCH(1539,2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: unable to inititalize BCH, bad parameters?
>>>

**Comment by dj-on-github** [comment]
After some fiddling, I found it was the t=1 poly that you use for all values of t.

**Comment by lolib11** [comment]
hello, 
I want to ask , 
" is the polynomial value changed with the t value even if we use default value of polynomial?"

because when I change polynomial parameter the ** RuntimeError: unable to inititalize BCH, bad parameters** error come 
I have different values of k and t !
